name: CI

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo prereleased!
